### ISSUE TITLE
 Invalid key 'noautocmd'

### ISSUE THREAD

**Issue by bommbo** [kevinhwang91/nvim-hlslens#10]
- `nvim --version`:v0.5.0-dev
- Operating system/version:manjaro

**Describe the bug**
Error executing vim.schedule lua callback: ...vim/plugged/nvim-hlslens/lua/hlslens/render/floatwin.lua:31: Invalid key 'noautocmd'

**非准确描述**
首先，非常抱歉，我可能没有办法先弄最小配置，然后提出哪里出了问题。我只能简单描述一下什么情况报错：
当 在长文件搜索，就会有上述报错。

**other**
非常感谢这个插件

translate from Google:

** Non-accurate description **

First of all, I am very sorry, I may have no way to get the smallest configuration first, and then I have made a problem. I can only describe what circumstances:

When searching in long files, there will be the above error.

** Other **

Thank you very much this plugin.

**Comment by kevinhwang91** [comment]
更新你的nvim，这个是上游api的改变。谢谢反馈。这个pr我暂时不关闭。

translate from Google:
Update your NVIM, this is the change in the upstream API. Thank you feedback. This PR I was not closed for the time being.

**Comment by bommbo** [comment]
> 更新你的nvim，这个是上游api的改变。谢谢反馈。这个issue我暂时不关闭。
> 
> translate from Google:
> Update your NVIM, this is the change in the upstream API. Thank you feedback. This issue I was not closed for the time being.

ok, 我更新好了，现在没问题了，你的扩展都非常不错。

**Comment by kevinhwang91** [comment]
It's time to close now.
