### ISSUE TITLE
Error arithmetic on field 'end_col' (a nil value)

### ISSUE THREAD

**Issue by ray-x** [kevinhwang91/nvim-hlslens#11]
- `nvim --version`: 
NVIM v0.6.0-dev+96-g5f01714b2
Build type: Release
LuaJIT 2.1.0-beta3

- Operating system/version:
 MacOS

**Describe the bug**
 Error message when search a text.  ` arithmetic on field 'end_col' (a nil value)`

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`

```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/nvim-hlslens'

call plug#end()
lua require('hlslens').setup()
noremap <silent> n <Cmd>execute('normal! ' . v:count1 . 'n')<CR>
            \<Cmd>lua require('hlslens').start()<CR>
noremap <silent> N <Cmd>execute('normal! ' . v:count1 . 'N')<CR>
            \<Cmd>lua require('hlslens').start()<CR>
noremap * *<Cmd>lua require('hlslens').start()<CR>
noremap # #<Cmd>lua require('hlslens').start()<CR>
noremap g* g*<Cmd>lua require('hlslens').start()<CR>
noremap g# g#<Cmd>lua require('hlslens').start()<CR>

" use : instead of <Cmd>
nnoremap <silent> <leader>l :nohlsearch<CR>
```

1. Search a string
2. see error 
```
Error executing vim.schedule lua callback: .../.config/nvim/plugged/nvim-hlslens/lua/hlslens/index.lua:135: attempt to perform
 arithmetic on field 'end_col' (a nil value)
```

**Expected behavior**
No error

**Screenshots**

**Additional context**

**Comment by kevinhwang91** [comment]
You need to rebuild your Neovim nightly or tag hlslens to https://github.com/kevinhwang91/nvim-hlslens/commit/ada900452b2f7100c5e6bafafb87ec2979f1b423 .

**Comment by kevinhwang91** [comment]
Has a variable to determine whether enable the nightly feature, I'm afraid you misunderstand hlslens doesn't work at 0.5 stable version, so I explain here and will update the README.

**Comment by jonathf** [comment]
This "bug" hit me and it took me a while to track down this issue.

Did you say that the README was updated?
Also, if ada9004 is the target for which neovim users with nightly builds should use, do you mind tagging it?

**Comment by kevinhwang91** [comment]
> This "bug" hit me and it took me a while to track down this issue.
> 
> Did you say that the README was updated? Also, if [ada9004](https://github.com/kevinhwang91/nvim-hlslens/commit/ada900452b2f7100c5e6bafafb87ec2979f1b423) is the target for which neovim users with nightly builds should use, do you mind tagging it?

I don't get what issue you are encountering. I suggest you rebuild your nightly version or use  0.5 version.
