### ISSUE TITLE
Conflict with vim-slash

### ISSUE THREAD

**Issue by I60R** [kevinhwang91/nvim-hlslens#12]
That plugin [remaps the same keys](https://github.com/junegunn/vim-slash/blob/31aee09b7ea8893a18fa34f65e63e364fc998444/plugin/slash.vim#L115) and because of that lenses wouldn't update.

Reproducible if both plugins are installed

**Comment by kevinhwang91** [comment]
`noremap <plug>(slash-after) <Cmd>lua require('hlslens').start()<CR>` is the solution. I don't know why you want `vim-slash`.
hlslens has a `calm_down` mode and I think `haya14busa/vim-asterisk` is neater than `vim-slash`

**Comment by I60R** [comment]
Honestly, I don't even remember when and why I installed it.

This issue was rather created to inform you as well as others who may have both plugins installed that the conflict exists, since it's not easy to debug and someone might easily guess that there's something wrong with your plugin.

BTW, Thank you for `vim-asterisk` suggestion, I'll certainly try it
