### ISSUE TITLE
Integration with lualine

### ISSUE THREAD

**Issue by kdheepak** [kevinhwang91/nvim-hlslens#14]
**Is your feature request related to a problem? Please describe.**

I'd like to disable virtual text but only show the contents of the virtual text for the nearest search in the status line. 

Is there a way to get that information? I tried `print(require'hlslens'.status())` but that just prints `start`.

**Comment by kevinhwang91** [comment]
Does `nearest_float_when = 'always'` work for you? If you prefer the `[number/count]` in statusline, you should request a feature for lualine to a component. It's very easy to use `searchcount()` to implement this feature.

**Comment by kdheepak** [comment]
When I use `nearest_float_when = 'always'`:

<img width="1000" alt="Screen Shot 2021-08-30 at 9 58 03 AM" src="https://user-images.githubusercontent.com/1813121/131368387-c8828a2e-3a78-4c8f-a911-484fd74b6ef8.png">

I would prefer it in one location. In lualine, a function that returns a string is a component. And I was wondering if I could use the string generated by this plugin. That way, I could use the `  override_lens` function to maybe customize the display and get the same format in the lualine statusline.

**Comment by kevinhwang91** [comment]
From the screenshot, look like you haven't turned on `termguicolors`, or your term is not supported true colors. The statusline will be transparent if true color is enabled.

>That way, I could use the override_lens function to maybe customize the display and get the same format in the lualine statusline.

No, you can't reuse the same format between `nvim_buf_set_extmark` and statusline eval. So the proper way is to request this feature to lualine.

**Comment by kdheepak** [comment]
Thanks! I’m pretty sure I have termguicolors though.  I think it is transparent. The statusline colors are different from my tabline colors when though they are using the same highlight groups.
