### ISSUE TITLE
[bug] virtual text doesnt appear

### ISSUE THREAD

**Issue by alexzanderr** [kevinhwang91/nvim-hlslens#17]
- `nvim --version`: 0.6
- Operating system/version: manjaro 21 xfce ornara (arch linux)

**Describe the bug**
i dont get any virtual text on the searches even with pasted config from your readme

quick demo for you to see:

https://user-images.githubusercontent.com/54772464/134736740-65522963-375b-4b99-b8da-3c776347eb04.mp4

i followed your instructions and for me virtual text doesnt appear just near the results.

**Comment by alexzanderr** [comment]
update:

after looking on use other issue on this repo:

my packer config look like this now:
```lua
	use {
		'kevinhwang91/nvim-hlslens',
		setup = [[vim.g.loaded_nvim_hlslens = 1]],
	}
```
and still, it doesnt work...

**Comment by kevinhwang91** [comment]
check out your statusline

**Comment by alexzanderr** [comment]
yeah, i saw that, thats why i've raised this issue, because its broken.

normally, the virtual text should be position to the right of the item that is found within the search.

**Comment by alexzanderr** [comment]
just like `undefined global issue`, but just for the items that im searching for.

**Comment by alexzanderr** [comment]
i want to have it like this

https://user-images.githubusercontent.com/17562139/115062493-fd26a100-9f1c-11eb-9305-20ef83d08e40.png


from your readme, but i respected the snippet that you gave us for virtual text, but it doesnt work.

**Comment by kevinhwang91** [comment]
minimal configuration, please

**Comment by alexzanderr** [comment]
configuration copy pasted from your [readme](https://github.com/kevinhwang91/nvim-hlslens/#customize-virtual-text)
```lua
require('hlslens').setup({
    calm_down = true,
    nearest_only = true,
    nearest_float_when = 'always',
    override_lens = function(render, plist, nearest, idx, r_idx)
        local sfw = vim.v.searchforward == 1
        local indicator, text, chunks
        local abs_r_idx = math.abs(r_idx)
        if abs_r_idx > 1 then
            indicator = ('%d%s'):format(abs_r_idx, sfw ~= (r_idx > 1) and '▲' or '▼')
        elseif abs_r_idx == 1 then
            indicator = sfw ~= (r_idx == 1) and '▲' or '▼'
        else
            indicator = ''
        end

        local lnum, col = unpack(plist[idx])
        if nearest then
            local cnt = #plist
            if indicator ~= '' then
                text = ('[%s %d/%d]'):format(indicator, idx, cnt)
            else
                text = ('[%d/%d]'):format(idx, cnt)
            end
            chunks = {{' ', 'Ignore'}, {text, 'HlSearchLensNear'}}
        else
            text = ('[%s %d]'):format(indicator, idx)
            chunks = {{' ', 'Ignore'}, {text, 'HlSearchLens'}}
        end
        render.set_virt(0, lnum - 1, col - 1, chunks, nearest)
	end
})
```

it doesnt work as presented in this [image](https://user-images.githubusercontent.com/17562139/115062493-fd26a100-9f1c-11eb-9305-20ef83d08e40.png)

**Comment by kevinhwang91** [comment]
```diff
-   nearest_only = true,
-   nearest_float_when = 'always',
```

**Comment by alexzanderr** [comment]
now its working

![image](https://user-images.githubusercontent.com/54772464/134811638-61f32c64-0ad8-4038-ace3-f706182e857b.png)


thank you so much!
