### ISSUE TITLE
redo is executed when issuing search using plugin 

### ISSUE THREAD

**Issue by 0xRZ** [kevinhwang91/nvim-hlslens#19]
Hello, thank you for the plugin.
Im encountering weird problem, so i have this mapping: `nnoremap <space>sn /<c-r><c-w><CR>`, and when i use it, seems like it also executes `:redo`, here is the gif demonstrating it. After i do `5D`, then `u`, then invoking search, `:redo` is executed without me pressing it, which deletes 5 row of 1's again. 

![Peek 2021-11-28 19-20](https://user-images.githubusercontent.com/46892933/143777614-a739cb41-fb79-4d82-956c-6c151e3bf240.gif)

init.vim i use:
```vim
call plug#begin()
Plug 'kevinhwang91/nvim-hlslens'
call plug#end()

noremap <silent> n <Cmd>execute('normal! ' . v:count1 . 'n')<CR>
            \<Cmd>lua require('hlslens').start()<CR>
noremap <silent> N <Cmd>execute('normal! ' . v:count1 . 'N')<CR>
            \<Cmd>lua require('hlslens').start()<CR>
noremap * *<Cmd>lua require('hlslens').start()<CR>
noremap # #<Cmd>lua require('hlslens').start()<CR>
noremap g* g*<Cmd>lua require('hlslens').start()<CR>
noremap g# g#<Cmd>lua require('hlslens').start()<CR>

nnoremap <space>sn /<c-r><c-w><CR>
nnoremap <space>/ :noh<CR>
```

`nvim --version`: NVIM v0.6.0-dev+640-gb51b0aecc

It's a strange problem, why this might be happening?

**Comment by kevinhwang91** [comment]
Thanks for your report, fixed now.
I think the commit message has told you the reason. 
I'm refactoring the code, BTW.
