### ISSUE TITLE
Support for `*`

### ISSUE THREAD

**Issue by axieax** [kevinhwang91/nvim-hlslens#20]
**Is your feature request related to a problem? Please describe.**

Would be very helpful to get virtual text highlights for occurrences of word under cursor with `*`.

**Describe the solution you'd like**

Support for observing `*`.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by kevinhwang91** [comment]
Read the README that has shown the solution.

**Comment by axieax** [comment]
Thanks I somehow missed that before oops. Also, in the same section for setting up vim-visual-multi, I'm not too sure if that still works anymore, since it seems that virtual text appears when entering visual_multi_start but disappears after using the keybind to go to the next word. Could you reproduce this or is it just me?

**Comment by kevinhwang91** [comment]
What issue do you talk about? normal *#/nN or extend vim-visual-multi?

**Comment by axieax** [comment]
extend vim-visual-multi

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-hlslens#integrate-with-other-plugins

Make sure the lua script works

**Comment by axieax** [comment]
Yep I literally copied and pasted that script, but lens don't seem to stay for some reason. Not sure if it's my issue or smth

**Comment by kevinhwang91** [comment]
`lua print(vim.inspect(require('vmlens')))`

**Comment by axieax** [comment]
Yep I'm mapping the script correctly (I do plugins.vmlens instead of vmlens), with that command displaying a table with exit and start functions as expected. The lens activates the first time but disappears on navigation, as can be seen in the video below

https://user-images.githubusercontent.com/62098008/143815735-d70be98c-dc6f-4b9b-a7f7-7fcce7dab0bb.mp4

:

**Comment by kevinhwang91** [comment]
Please open a new issue for vim-visual-multi. More info and mini config is required.

**Comment by axieax** [comment]
Wait is this an issue with nvim-hlslens or vim-visual-multi (since it's todo with the lens)? Also, the config is just the README script copied and pasted into plugins/vmlens.lua :p

**Comment by kevinhwang91** [comment]
For nvim-hlslens, I think we're talking about is off-topic under this issue and insufficient info.

Please run `nvim -u mini.vim` or `nvim -u mini.lua`, mini.vim/lua must `so vm.lua` and reproduce the issue.

**Comment by axieax** [comment]
Here is a demo with the minimal config. As can be seen, normal `/` works as expected, but still not for vim-visual-multi still. Also, sorry for going off topic, would you like to move this conversation to a new issue? I just wanted to know whether the integration is working for you as well :)

https://user-images.githubusercontent.com/62098008/143818871-f70158ab-9fab-4e5b-b4ec-f901ab0e7275.mp4

**Comment by kevinhwang91** [comment]
> I just wanted to know whether the integration is working for you as well 
Absolutely yes.
