### ISSUE TITLE
Option to add callback to lens instead of override_lens

### ISSUE THREAD

**Issue by petertriho** [kevinhwang91/nvim-hlslens#22]
**Is your feature request related to a problem? Please describe.**
Not really, but would like to make it cleaner to integrate with my own plugin.

**Describe the solution you'd like**
I was wondering if it would be possible for you to add something like "lens_callback" (similar to override_lens) but instead of overriding, it just calls the function instead

**Comment by kevinhwang91** [comment]
Do you want to get the position range after the index is built?

**Comment by petertriho** [comment]
Yes, that's the intention

**Comment by kevinhwang91** [comment]
Please try `dev` branch.
And add 
```lua
    require('hlslens').setup({
        build_position_cb = function(plist, bufnr, changedtick, pattern)    
            require('scrollbar').search_handler.show(plist.start_pos)
        end
    })
```

If you have no problem, I will improve the documentation.

**Comment by petertriho** [comment]
Works perfectly, thank you!

**Comment by kevinhwang91** [comment]
Only fire once if the index is built instead of moving the cursor, please note.

`changedtick` or `pattern`  is changed, the index will refresh and fire this callback.
