### ISSUE TITLE
Virtual text displayed for current line only when `asterisk#keeppos` option is set

### ISSUE THREAD

**Issue by gbcreation** [kevinhwang91/nvim-hlslens#23]
- `nvim --version`:
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compilé par builduser

Features: +acl +iconv +tui

**Describe the bug**

When nvim-hlslens is used with vim-asterisk as described in the **Integrate with other plugins** section of the README and the keepCursor feature of vim-asterisk is enabled with `let g:asterisk#keeppos = 1`, virtual texts of nvim-hlslens are:

- all displayed if `*` is hit when the cursor is on the first character of a word
- displayed only for the current line if `*` is hit when the cursor is not at the first character of a word

1. move the cursor on the second character of a word
2. hit `*`

**Expected behavior**

All virtual texts should be displayed.

**Screenshots**

* Use case 1: result after hitting `*` when cursor is on the letter `a` of the first line

![Screenshot_20220113_231021](https://user-images.githubusercontent.com/454315/149416985-4356878b-df9a-47b3-bd91-41226f70d41b.png)

* Use case 2: result after hitting `*` when cursor is on the letter `b` of the first line

![Screenshot_20220113_231049](https://user-images.githubusercontent.com/454315/149417030-5cac1c4b-5c6b-495e-aaec-878bdf28a5b3.png)

**Comment by kevinhwang91** [comment]
Thanks, fixed now.

**Comment by kevinhwang91** [comment]
There are some problems with indicators, this is the reason why I didn't show lens before, need fix now.
