### ISSUE TITLE
`calm_down` does not work with Asterisk

### ISSUE THREAD

**Issue by gbcreation** [kevinhwang91/nvim-hlslens#26]
- `nvim --version`: NVIM v0.6.1 / LuaJIT 2.1.0-beta3
- Operating system/version: ArchLinux

**Describe the bug**

When the keymaps are configured to use Asterisk like this:

```
vim.api.nvim_set_keymap('n', '*', "<Plug>(asterisk-*)<Cmd>lua require('hlslens').start()<CR>", {})
vim.api.nvim_set_keymap('n', '#', "<Plug>(asterisk-#)<Cmd>lua require('hlslens').start()<CR>", {})
vim.api.nvim_set_keymap('n', 'g*', "<Plug>(asterisk-g*)<Cmd>lua require('hlslens').start()<CR>", {})
vim.api.nvim_set_keymap('n', 'g#', "<Plug>(asterisk-g#)<Cmd>lua require('hlslens').start()<CR>", {})
```

and the `calm_down` option is set to `true`, moving the text cursor out of the currently highlighted word does not disable the search highlighting.

**Comment by kevinhwang91** [comment]
I can't reproduce the issue. Does hlslens under `calm_down = true` work fine without `asterisk`?

And what' are your settings of `asterisk`?

**Comment by gbcreation** [comment]
After testing various configurations, I can no longer reproduce this issue with the original one. Maybe an issue with my plugin manager :thinking:  (I'm using Packer).
