### ISSUE TITLE
The plugin modifies the background color of the status bar

### ISSUE THREAD

**Issue by denstiny** [kevinhwang91/nvim-hlslens#27]
https://user-images.githubusercontent.com/57088952/154847525-d2573172-41bc-44db-bfb0-dbc8333684cf.mp4

**Comment by kevinhwang91** [comment]
Have you entered fzf using bqf?

**Comment by denstiny** [comment]
I don't quite understand what you mean, what should I do, this is my configuration
```lua
require('hlslens').setup({
    calm_down = true,
    nearest_only = true,
    nearest_float_when = 'always'
})

vim.api.nvim_set_keymap(
	"n",
	"n",
	"<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>",
	{ noremap = true, silent = true }
)
vim.api.nvim_set_keymap(
	"n",
	"N",
	"<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>",
	{ noremap = true, silent = true }
)
vim.api.nvim_set_keymap("n", "*", "*<Cmd>lua require('hlslens').start()<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "#", "#<Cmd>lua require('hlslens').start()<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "g*", "g*<Cmd>lua require('hlslens').start()<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "g#", "g#<Cmd>lua require('hlslens').start()<CR>", { noremap = true })

vim.api.nvim_set_keymap("n", "<leader>l", ":noh<CR>", { noremap = true, silent = true })

```

**Comment by kevinhwang91** [comment]
Sorry, I misunderstand this repo as my other plugin `nvim-bqf`.

**Comment by kevinhwang91** [comment]
Look like a theme issue,  hlslens will use `Ignore`  highlight group to render padding text. In general, `Ignore` should be `Ignore         xxx ctermfg=0 guifg=bg`.

**Comment by denstiny** [comment]
I tried :hi Ignore guifg=red guifg=red ctermfg=red ctermbg=red, but it didn't work

**Comment by denstiny** [comment]
![图片](https://user-images.githubusercontent.com/57088952/154872359-7d180f94-d0e4-4671-9f6d-6a74e7d39087.png)
I tried :hi Ignore guifg=red guibg=red ctermfg=red ctermbg=red , the inactive area background is still black

**Comment by kevinhwang91** [comment]
What's your `stl`?

**Comment by denstiny** [comment]
![图片](https://user-images.githubusercontent.com/57088952/154931645-b4f8f2fe-b3e7-4fdd-89b4-ebfc2662150b.png)

**Comment by kevinhwang91** [comment]
`float_shadow_blend = 100` should work.

**Comment by denstiny** [comment]
> `float_shadow_blend = 100` should work.

Thank you very much
