### ISSUE TITLE
Matches all empty strings when using `:let @/ = ""` to clear the search pattern.

### ISSUE THREAD

**Issue by K41eb** [kevinhwang91/nvim-hlslens#28]
- `nvim --version`: v0.6.1
- Operating system/version: Linux arch 5.16.2-arch1-1

**Describe the bug**
Clearing the search pattern "the intended way" (not with the `hlsearch` option, because it disables highlighting) makes `hlslens` match all empty string in the document.

https://stackoverflow.com/a/657484
As stated in the above Stack verflow answer, and unless nvim does anything different, `:let @/ = ""` clears the search pattern and does not set it to "empty string". However `hlslens` does interpret it as empty stirng and matches all empty strings of the document, which is inconvenient.

http://vimdoc.sourceforge.net/htmldoc/pattern.html#last-pattern

**To Reproduce using `nvim -u mini.lua`**

Example:
`cat mini.lua`

```lua
-- packer
use {'kevinhwang91/nvim-hlslens'}
```

1. `/anything`
2. `:let @/ = ""`
3. Enjoy?

**Expected behavior**
`hsllens` should not match anything.

**Screenshots**

![Screenshot](https://i.ibb.co/CsdZNWZ/2022-03-09-02-12-18-01-00.png "Screenshot")

**Comment by K41eb** [comment]
Remark / question: using `nohlsearch` to disable the highlighting causes the virtual text to linger until the cursor is moved. Is there any way to have it react more quickly?

**Comment by kevinhwang91** [comment]
Fixed now.
