### ISSUE TITLE
Does nvim-hlslens provide same functions like vim-visual-star-search?

### ISSUE THREAD

**Issue by fannheyward** [kevinhwang91/nvim-hlslens#29]
Is there any to do `*` searching with visual selection, likes https://github.com/bronson/vim-visual-star-search?

**Comment by kevinhwang91** [comment]
Is https://github.com/kevinhwang91/nvim-hlslens#integrate-with-other-plugins you want?

**Comment by fannheyward** [comment]
My mistake, I'm not going to integrate nvim-hlslens with vim-visual-star-search, but can nvim-hlslens provide the _same_ functions, `*` does visual-selection-search, without using vim-visual-star-search?

**Comment by kevinhwang91** [comment]
> I found `x` mode support in the README doc, I thought nvim-hlslens provided this, but in my tests, it doesn't work.

My fault, I updated the README a month ago and hadn't realized bare `*` in visual mode do the unexpected action.

nvim-hlslens only get the index from the pattern and render UI, never do any navigations.
