### ISSUE TITLE
hlslens doesn't work after recently neovim commit

### ISSUE THREAD

**Issue by rhcher** [kevinhwang91/nvim-hlslens#33]
I tested some recently version nvim and find it beacause this neovim [commit](https://github.com/neovim/neovim/pull/18461/commits), I don't know if it a neovim bug and what is core reason, So I just open issue here and ask for your help.

**Comment by kevinhwang91** [comment]
Thanks, hlslens use ffi. Fix now, but I think we should add tests for the ffi interface.
