### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by wbaes** [kevinhwang91/nvim-hlslens#35]
- `nvim --version`: NVIM v0.8.0-dev+374-ge13dcdf16
- Operating system/version: Arch Linux 5.18.3-arch1-1

**Describe the bug**
After pressing 'n' a certain number of times (it varies, sometimes it happens after 1, sometimes after around 4 or 5) after searching with /, nvim crashes with a segmentation fault.

1. Search a term using /
2. Press 'n' to look for the next one
3. Repeat until neovim crashes

**Expected behavior**
Neovim not to crash

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-hlslens/issues/33

Rebuild nvim.
