### ISSUE TITLE
Incorrect(?) documentation for override_lens

### ISSUE THREAD

**Issue by qubidt** [kevinhwang91/nvim-hlslens#36]
the README, [currently](https://github.com/kevinhwang91/nvim-hlslens/blame/6cd78e73b28af4618cf67a470e53e13d59899914/README.md), describes `override_lens` as:

```lua
@param bufnr (number) buffer number
@param splist (table) (1,1)-indexed position
@param nearest (boolean) whether nearest lens
@param idx (number) nearest index in the plist
@param relIdx (number) relative index, negative means before current position, positive means after
```

Is the `bufnr` annotation correct? The override function seems to be passed the entire render object:

https://github.com/kevinhwang91/nvim-hlslens/blob/6cd78e73b28af4618cf67a470e53e13d59899914/lua/hlslens/render.lua#L103-L106

**Comment by kevinhwang91** [comment]
Thanks, have corrected it.
