### ISSUE TITLE
<Shift-s> and <Shift-3> support

### ISSUE THREAD

**Issue by Integralist** [kevinhwang91/nvim-hlslens#38]
**Is your feature request related to a problem? Please describe.**
I use `<Shift-s>` and `<Shift-3>` to search (forward/backwards) for the word under the cursor, and I realised this plugin doesn't support that.

**Describe the solution you'd like**
The ability to press `<Shift-s>` and have the current word under my cursor become the search term so I don't have to type out the word manually. Same for `<Shift-3>` but just search in reverse.

**Comment by kevinhwang91** [comment]
I don't know what you are talking about.

**Comment by Integralist** [comment]
Basically I was referring to `*` which in vim triggers a forward search of the word under the cursor.

e.g. if my buffer looks like the following...

```
foo
bar
foo
baz
```

...if my cursor is on the word `foo` in the first line and I press `*` then vim starts a forward search to the next occurrence of the word `foo`. 

But the hlslens plugin doesn't activate if I do that. It'll only activate if I type a search `/foo`. This is fine, but if I have a longer word I'm searching for being able to just press `*` is much more convenient than manually typing.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-hlslens#vim-asterisk
