### ISSUE TITLE
Labels are not removed when using `vim.cmd('nohl')` but works when using `:nohl`

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [kevinhwang91/nvim-hlslens#40]
- `nvim --version`: NVIM v0.8.0-dev-f98cff957-dirty
- Operating system/version: macOS 10.15.7

**Describe the bug**

This is the expected behavior when using `:nohl` to clear matches

1. search is started using `*` under word `path`
![image](https://user-images.githubusercontent.com/2790520/189715034-82e40ca5-a2ea-4254-9c61-04f9bed6c52e.png)
2. run command `:nohl` and results are cleared as expected
![image](https://user-images.githubusercontent.com/2790520/189715205-6816319c-8cfc-4fe6-8e1e-1c66a517a54c.png)

and this is the bug when using `vim.cmd('nohl')` from lua
1. search is started using `*` under word `path`
![image](https://user-images.githubusercontent.com/2790520/189715034-82e40ca5-a2ea-4254-9c61-04f9bed6c52e.png)
2. run command `:lua vim.cmd('nohl')`
![image](https://user-images.githubusercontent.com/2790520/189715712-8a1e8377-622a-47bb-b9e6-f48e84defd98.png)
3. when moving cursor to next/previous line all matches are removed

**To Reproduce using `nvim -u mini.lua`**

Example:
`cat mini.lua`

```lua
-- packer
use {'kevinhwang91/nvim-hlslens'}

local kopts = {noremap = true, silent = true}

vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)

vim.api.nvim_set_keymap('x', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('x', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('x', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('x', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)

vim.api.nvim_set_keymap('n', '<Leader>l', ':noh<CR>', kopts)
```

1. start a match with `*`
2. run `:lua vim.cmd('nohl')`
3. check matches are still there on screen

**Expected behavior**
All matches are cleared

**Screenshots**
posted in the describe bug section

**Comment by kevinhwang91** [comment]
#### Stop hlslens

Hlslens will observe whether `nohlsearch` command is accepted.

1. Run ex command `nohlsearch`
2. Map key to `:nohlsearch`, make sure that to use `:` instead of `<Cmd>`

**Comment by kevinhwang91** [comment]
It's expected. `vim.cmd` doesn't fire the event.
