### ISSUE TITLE
Disable Nearest Highlight During Substitute

### ISSUE THREAD

**Issue by CallumHoward** [kevinhwang91/nvim-hlslens#41]
**Is your feature request related to a problem? Please describe.**

When doing substitution on a search map, the Nearest Highlight remains during the substitution.
For example, 

```lua
    hl.TelescopePromptTitle = {
      bg = c.bg_dark,
      fg = c.fg_dark,
    }
    hl.TelescopePreviewTitle = {
      bg = c.bg_dark,
      fg = c.fg_dark,
    }
```

<img width="360" alt="Screen Shot 2022-09-23 at 10 03 20 am" src="https://user-images.githubusercontent.com/7144420/191871324-783c2d8a-28a4-4ceb-8e08-2fcee9a715f7.png">

and in nvim:
```viml
/fg_dark
:%s//foo_bar_baz/g
```
(Where empty substitute pattern uses previous search)

I get:

<img width="332" alt="Screen Shot 2022-09-23 at 9 43 42 am" src="https://user-images.githubusercontent.com/7144420/191870293-12b90179-b8f4-41cb-bd72-7f7f614dd9be.png">

I would like:

<img width="355" alt="Screen Shot 2022-09-23 at 9 57 39 am" src="https://user-images.githubusercontent.com/7144420/191870886-a72ce893-0332-4ad8-b2da-1f0bea759c7c.png">

I think this can be achieved by possibly disabling hls-lens before substituting and re-enabling after, but I don't see any autocommands like `SubstitueEnter` and `SubstituteLeave` that could be used to hook into...

**Comment by kevinhwang91** [comment]
I will support incsearch for `vimgrep`, `vimgrepadd`, `lvimgrep`, `lvimgrepadd` and `global`  first.

**Comment by kevinhwang91** [comment]
Try Neovim 0.8 and the latest code. Neovim 0.8 shall be released at the end of this month.

**Comment by CallumHoward** [comment]
That works great, thank you!
