### ISSUE TITLE
Hlslens causes `E5500: autocmd has thrown an exception` when trying to run command in visual mode

### ISSUE THREAD

**Issue by wustho** [kevinhwang91/nvim-hlslens#42]
- `nvim --version`: v0.8.0-dev-1152-g14610332b
- Operating system/version: Ubuntu 20.04.4 LTS x86_64

**Describe the bug**
Whenever I tried doing commands on visually selected lines with hlslens installed (by packer) I got this:

```
:'<,'>n
E5500: autocmd has thrown an exception: Vim(lua):E16: Invalid range
:'<,'>no
E5500: autocmd has thrown an exception: Vim(lua):E481: No range allowed
:'<,'>nor
E5500: autocmd has thrown an exception: Vim(lua):E481: No range allowed
:'<,'>norm A')
```

1. Open any files
2. Do VISUAL LINE (`V`) on some lines
3. Try to do `norm` command on visually selected lines: `:'<,'>norm A')`

**Expected behavior**
It should works

**Screenshots**

![Screenshot_20220925_111506](https://user-images.githubusercontent.com/43810055/192128694-0145edd3-bc63-43b7-ab31-9d7860236759.png)

**Additional context**
I tried uninstalling all my plugins to troubleshoot this, and what cause this issue is hlslens. Other than that, it's awesome plugins btw. Thanks.

**Comment by kevinhwang91** [comment]
Reproduced. Introducing this issue by recently reworking.
