### ISSUE TITLE
Support Sexy_scroller.vim smooth scrolling.

### ISSUE THREAD

**Issue by lkhphuc** [kevinhwang91/nvim-hlslens#44]
Currently hlslens does not work with [Sexy_scroller.vim](https://github.com/joeytwiddle/sexy_scroller.vim), the best smooth scrolling plugin IMO I've tried so far. 

**Describe the solution you'd like**
Just work with sexy_scroller likes with other smooth_scroll plugins.

**Describe alternatives you've considered**
It does work with other plugin like neoscroll though, so this could very well be due to the way sexy scroller is implemented.
From their README, I saw some notes about special handling of `/` command but I'm not very familiar with neovim internal to understand that.

**Comment by kevinhwang91** [comment]
I just give it a try, work for me.

**Comment by lkhphuc** [comment]
Thanks, I will check further. For me hlslens sometimes works, sometime doesn't. Couldn't quite figure out the pattern yet it most likely to not work if the screen is scrolled during incsearch.

**Comment by lkhphuc** [comment]
Turned out I don't have the "Minimal config" setup like in the README.
Everything was working fine for me without the minimal config so I never notice, but after adding that in it works great with sexy_scroller now. 

Thanks.
