### ISSUE TITLE
show only count option and disable jump labels?

### ISSUE THREAD

**Issue by GNOMES** [kevinhwang91/nvim-hlslens#50]
Apologies If I am misunderstanding the options in the "Setup and description" section of the README.

If someone wanted to use this plugin without the jumping features is there a way to hide the [3N 2], [n 2] like tags, but leave the x/y results for the current line? 

It seems like /<string> + control g (do not hit enter) gives me the result I want, but using n/N is faster. 

Context: 
My Neovim is currently configured with "cmdheight = 0",  being able to quickly search a log file to count for occurences of say an error string, is the main feature I find I have lost since using cmdheight = 0.

This plugin is working great to add that functionality back, but I am wanting to hide the jump tags so that I only get the info I need so it is cleaner.

**Comment by kevinhwang91** [comment]
`nearest_only = true`
