### ISSUE TITLE
Continue hlslens after :nohlsearch

### ISSUE THREAD

**Issue by simonmandlik** [kevinhwang91/nvim-hlslens#51]
When I search for a pattern, hlslens is working and showing the hints. If I stop the highlighting with `:nohlsearch`, hlslens disappears.

But then, the search can be invoked again e.g. by pressing `n` and in this case, hlslens hints are no longer showing.

Would it be possible to update the minimal configuration to also take this into account?

Thanks!

**Comment by kevinhwang91** [comment]
```lua
vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
```
is the content in README and the issue template.

**Comment by simonmandlik** [comment]
Thank you!
