### ISSUE TITLE
Link HlSearchNear to CurSearch instead

### ISSUE THREAD

**Issue by opalmay** [kevinhwang91/nvim-hlslens#54]
This better matches the way search works without the plugin. For some themes they're the same, for others not (e.g. Catppuccin)
Could also potentially link the virtual text too to match.

**Comment by kevinhwang91** [comment]
No `CurSearch` in the built-in highlight group.

**Comment by opalmay** [comment]
This is the one I'm referring to:
`:h hl-CurSearch`
![image](https://user-images.githubusercontent.com/65673442/203651680-05cfb8db-5448-4074-ae08-4df4b6f07c13.png)

**Comment by kevinhwang91** [comment]
https://github.com/vim/vim/commit/a43993897aa372159f682df37562
It's a new group in Neovim 0.8, need to wait for a while. You can link by yourself for now.
