### ISSUE TITLE
nvim-hlslens need to invoke `require('nvim-hlslens').setup()` to boot!

### ISSUE THREAD

**Issue by gmr458** [kevinhwang91/nvim-hlslens#55]
- `nvim --version`: NVIM v0.8.1
- Operating system/version: Fedora Workstation 36

**Describe the bug**
Packer allows us to setup a plugin with the `config` option like this:
```lua
-- file lua/plugins.lua
return require("packer").startup(function(use)
	-- Packer can manage itself
	use("wbthomason/packer.nvim")

	use({
		"kevinhwang91/nvim-hlslens",
		config = function()
			require("hlslens").setup()
		end,
	})
end)
```
but when I call `require("hlslens").setup()` inside the config option this message appears: `nvim-hlslens need to invoke require('nvim-hlslens').setup() to boot!`

The message does not appear when I call it outside in other file like this:
```lua
-- file init.lua
require("plugins")
require("hlslens").setup()
```

Call `require('hlslens').setup()` inside the config options that packer.nvim provides.

**Expected behavior**
Call `require('hlslens').setup()` inside the config option that packer.nvim provides without errors.

**Screenshots**
![20221202_22h50m06s_grim](https://user-images.githubusercontent.com/53343401/205421295-ce22163f-35d2-4770-9f60-9f22ca5242d8.png)

**Comment by kevinhwang91** [comment]
It's weird. `~/.config/nvim/plugin/packer_compiled.lua` should be loaded before any plugins. What's your rtp?
`set rtp?`

**Comment by gmr458** [comment]
so it is necessary to use :PackerCompile?, if this is how you have designed it you can close the issue

**Comment by kevinhwang91** [comment]
Yes, this notification just is compatible with the elder version.

**Comment by DragonflyRobotics** [comment]
I am using Lazy, and I get this error message. I am using the setup function as the quickstart guide suggests and it works just fine but still gives me an error at the start. Is it because I might be lazyloading it?
