### ISSUE TITLE
[Cross-Plugins] Conflict of NeoClear.lua

### ISSUE THREAD

**Issue by nyngwang** [kevinhwang91/nvim-hlslens#56]
- `nvim --version`: `NVIM v0.9.0-dev-436+ga0dd663c2`
- Operating system/version: macOS 13.1

**Describe the bug**
I want to use your plugin with my own one https://github.com/nyngwang/NeoClear.lua. If I run `:NeoClear` and then type `n`(or `N`) again to jump to the next(or previous) word, the counter of occurrence will disappear. While I did find a workaround(code provided below), I'm thinking about how to get rid of the workaround code by fixing it upstream. 

**To Reproduce using `nvim -u mini.lua`**

```lua
use {
  'petertriho/nvim-scrollbar', -- This plugin requires your plugin.
  requires = {
    'kevinhwang91/nvim-hlslens',
    config = function ()
      vim.keymap.set('n', 'n', function ()
        vim.cmd([[
          silent! normal! n
          lua require('hlslens').start()
        ]])
      end, NOREF_NOERR_TRUNC)
      vim.keymap.set('n', 'N', function ()
        vim.cmd([[
          silent! normal! N
          lua require('hlslens').start()
        ]])
      end, NOREF_NOERR_TRUNC)
    end
  },
  config = function ()
    require('scrollbar.handlers.search').setup()
    require('scrollbar').setup {}
  end
}
```

1. Type `/require` or any other word that occurs many times in your current buffer.
2. Type `n`. You will see the occurrence counter of hlslens
3. Type `:NeoClear`.
4. Do. 2. again. You will not see the occurrence counter this time.

**Expected behavior**
I can always see the occurrence counter whether I call `:NeoClear` or not.

**Screenshots**

**Additional context**
Maybe this is related to my code: https://github.com/nyngwang/NeoClear.lua/blob/main/lua/neo-clear.lua#L10_L11

**Comment by kevinhwang91** [comment]
No idea how to fix it. All components of hlslens depend on `hlsearch` is on.

**Comment by nyngwang** [comment]
@kevinhwang91 When you finish searching a word and you want to clear its highlighting, would you call `:noh`?

**Comment by kevinhwang91** [comment]
> the next time pressing n or N the counter of your plugin disappears.

I tried [NeoClear.lua](https://github.com/nyngwang/NeoClear.lua) just now, but can't reproduce it. `n` or `N` will work again.

**Comment by nyngwang** [comment]
@kevinhwang91 So the two both work without these cmd?

```lua
local NOREF_NOERR_TRUNC = { noremap = true, silent = true, nowait = true }

vim.keymap.set('n', 'n', function ()
  vim.cmd([[
    silent! normal! n
    lua require('hlslens').start()
  ]])
end, NOREF_NOERR_TRUNC)
vim.keymap.set('n', 'N', function ()
  vim.cmd([[
    silent! normal! N
    lua require('hlslens').start()
  ]])
end, NOREF_NOERR_TRUNC)
```

**Comment by kevinhwang91** [comment]
It's your config issue. [NeoClear.lua](https://github.com/nyngwang/NeoClear.lua) + hlslens with mini config will work in neovim 0.8 in docker.

**Comment by nyngwang** [comment]
@kevinhwang91 Thanks for your testing. Sorry that I just realized the minimal config in your README.md is actually doing the same thing: that is, calling `require('hlslens').start()` is required. Since I was reviewing old config and I thought my provided code is a hotfix or something and tried to simplify it. Problem solved, great plugin!

```lua
require('hlslens').setup()

local kopts = {noremap = true, silent = true}

vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
```
