### ISSUE TITLE
Center text without disabling hlslens.

### ISSUE THREAD

**Issue by A-Lamia** [kevinhwang91/nvim-hlslens#57]
### Feature
So i have have some hotkeys eg, `nzzzv` to keep each jump centered, issue is zz and zv will disable hlslense. I've made a function that does the same thing when pressing enter when finalizing my search with the same issue.

### Resolve 
a setting that enables this feature natively.

**Comment by kevinhwang91** [comment]
Can't reproduce it, pls follow github template.

**Comment by A-Lamia** [comment]
I'm a little confused, what can't you reproduce ? `zz` hiding hlslens ?

**Comment by kevinhwang91** [comment]
> issue is zz and zv will disable hlslense.

Maybe the culprit is other plugins.

**Comment by A-Lamia** [comment]
I thought this was just how hlslens worked? press any key and it hides the search ?

**Comment by kevinhwang91** [comment]
If `calm_down = false`, it will clear lens if hlslens find `v:hlsearch` becomes 0.
If `calm_down = true`, it will also clear lens if cursor is out of matched ranges.

**Comment by A-Lamia** [comment]
Ok, so if after any keypress hlslens get's cleared while still being in range, that is not default behavior and is more then likely an issue with my config?

**Comment by A-Lamia** [comment]
Sorry if im bothering you i though i would just ask here how 
`require("hlslens").start()` works ? I'm using it in a custom function but for a key map but it doesn't seem to do anything.

**Comment by kevinhwang91** [comment]
> how require("hlslens").start() works ?

It's hard to explain, should RTFSC. https://github.com/kevinhwang91/nvim-hlslens/blob/7fb804f504fd0935d65246a1d5ddea73d9ceefc9/lua/hlslens/render/init.lua#L368

`let v:hlsearch = 0` , `set nohlsearch` and `noh` will clear all lens.
