### ISSUE TITLE
Bug about ufo support

### ISSUE THREAD

**Issue by XXiaoA** [kevinhwang91/nvim-hlslens#59]
- `nvim --version`: nightly
- Operating system/version: arch linux

**Describe the bug**
Look at the video, the count increase;

https://user-images.githubusercontent.com/62557596/210085076-a3eff465-dd56-4cb2-965e-ecac0bc4c62b.mp4

**To Reproduce using `nvim -u mini.lua`**
Copied from the readme
```lua
-- packer
use {'kevinhwang91/nvim-ufo', requires = 'kevinhwang91/promise-async'}

-- if Neovim is 0.8.0 before, remap yourself.
local function nN(char)
    local ok, winid = hlslens.nNPeekWithUFO(char)
    if ok and winid then
        -- Safe to override buffer scope keymaps remapped by ufo,
        -- ufo will restore previous buffer keymaps before closing preview window
        -- Type <CR> will switch to preview window and fire `tarce` action
        vim.keymap.set('n', '<CR>', function()
            local keyCodes = api.nvim_replace_termcodes('<Tab><CR>', true, false, true)
            api.nvim_feedkeys(keyCodes, 'im', false)
        end, {buffer = true})
    end
end

vim.keymap.set({'n', 'x'}, 'n', function() nN('n') end)
vim.keymap.set({'n', 'x'}, 'N', function() nN('N') end)
```

1. enter nvim and search a keyword only in one ufo fold
2. pressing `n`

**Expected behavior**
Show the current count, `2` in the video

**Comment by kevinhwang91** [comment]
The bottom index/count is not related to hlslens and ufo, check out your plugins.
