### ISSUE TITLE
Lens flicker on file write

### ISSUE THREAD

**Issue by MunifTanjim** [kevinhwang91/nvim-hlslens#63]
- `nvim --version`:
- Operating system/version:

**Describe the bug**

**To Reproduce using `nvim -u mini.lua`**

Example:
`cat mini.lua`

```lua
-- packer
use {'kevinhwang91/nvim-hlslens'}

require('hlslens').setup()

local kopts = {noremap = true, silent = true}

vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)

vim.api.nvim_set_keymap('x', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('x', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('x', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('x', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)

vim.api.nvim_set_keymap('n', '<Leader>l', ':noh<CR>', kopts)
```

1. Search for something using `*` or `/`
2. Clear highlight using `:nohl`
3. Write the file using `:w`
4. Keep repeating step 3, sometimes the highlights and lens will be visible for a short time

**Expected behavior**

Saving a file shouldn't cause flicker.

**Screenshots**

![Kapture 2023-06-02 at 16 15 39](https://github.com/kevinhwang91/nvim-hlslens/assets/8050659/04ef491f-bb96-4bb3-a3a8-e6a4c44324e4)

**Additional context**

https://github.com/kevinhwang91/nvim-hlslens/blob/5e3e9088fba7508cee3612ee50b14dfdd3ab19af/lua/hlslens/cmdline/init.lua#L330-L334

The flicker is triggered from this code.

**Comment by kevinhwang91** [comment]
Can't reproduce it, maybe some script change your `hlsearch`.

**Comment by MunifTanjim** [comment]
Okay, I reproduced it like this:

```
  vim.api.nvim_create_autocmd("BufWritePre", {
    buffer = bufnr,
    callback = function()
      vim.wait(2000)
    end,
  })
```

- Search for something using `*` or `/`
- Clear highlight using `:nohl`
- Write the file using `:w`
- When the `vim.wait` is happening, move the cursor (e.g. press `j`)
- Every once in a while search highlight and lens will flicker

Here `vim.wait(2000)` is artificially delaying the file save. But in my actual config it happens because of lsp code formatting that runs before the buffer is written.

**Comment by mortymacs** [comment]
I have the same problem. When I save a file, it shows the lens quickly on every line and then disappears.
My config: 
```lua
require("hlslens").setup()
```

**Comment by Rekwass** [comment]
I am able to reproduce the issue with the following config:
`minimal.lua`
```lua
vim.env.LAZY_STDPATH = '.repro'
load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()

vim.api.nvim_create_autocmd("BufWritePre", {
    callback = function()
        vim.wait(10)
        vim.cmd("m +1")
        vim.cmd("m -2")
    end,
})

require('lazy.minit').repro {
    spec = {
        {
            'kevinhwang91/nvim-hlslens',
            config = function()
                require('hlslens').setup()
            end,
            lazy = false,
        },
    },
}
```
In order to see the flickering follow these steps:

1. Create a file and add a couple lines to highlight
`main.cpp`
```cpp
int main() {
  int foo = 1;
  int bar = 2;

  int foobar = foo + bar;

  return foobar;
}
```
2. Open this file with the `minimal.lua` configuration with `nvim --clean -u minimal.lua main.cpp`
3. Highlight a word. *int* for example
4. Save the file with `:w` Repeat this step as it is **really inconsistent**.

I was using a mapping to invoke `:noh`

I worked around the issue with [this](https://stackoverflow.com/a/657484/12887055) answer on stackoverflow.

**Comment by kevinhwang91** [comment]
> I am able to reproduce the issue with the following config: `minimal.lua`
> 
> ```lua
> vim.env.LAZY_STDPATH = '.repro'
> load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()
> 
> vim.api.nvim_create_autocmd("BufWritePre", {
>     callback = function()
>         vim.wait(10)
>         vim.cmd("m +1")
>         vim.cmd("m -2")
>     end,
> })
> 
> require('lazy.minit').repro {
>     spec = {
>         {
>             'kevinhwang91/nvim-hlslens',
>             config = function()
>                 require('hlslens').setup()
>             end,
>             lazy = false,
>         },
>     },
> }
> ```
> 
> NVIM v0.10.1 Build type: Release LuaJIT 2.1.1725453128
> 
> In order to see the flickering follow these steps:
> 
> 1. Create a file and add a couple lines to highlight
>    `main.cpp`
> 
> ```c++
> int main() {
>   int foo = 1;
>   int bar = 2;
> 
>   int foobar = foo + bar;
> 
>   return foobar;
> }
> ```
> 
> 2. Open this file with the `minimal.lua` configuration with `nvim --clean -u minimal.lua main.cpp`
> 3. Highlight a word. _int_ for example
> 4. Then disable highlight with `:noh`
> 5. Save the file with `:w`. Repeat this step as it is **really inconsistent**
> 
> ![nvim-hlslens highlight flickering](https://private-user-images.githubusercontent.com/72019227/369600797-4d766642-e99f-4635-b7cf-25559df85456.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjQ4NzAsIm5iZiI6MTcyNjkyNDU3MCwicGF0aCI6Ii83MjAxOTIyNy8zNjk2MDA3OTctNGQ3NjY2NDItZTk5Zi00NjM1LWI3Y2YtMjU1NTlkZjg1NDU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDEzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNDdjZTI4ODE5YTk4NGU0ZjFhNzE5ZGM1MmMxODE1ZmUzYjQwZDEzYzk5MDljNjBiYmM2ZGZmYzZiMWY2YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9VALNurnesX7rAWcQHmwCMfud2jNOVmsCzVDqWMjX7w) [ ![nvim-hlslens highlight flickering](https://private-user-images.githubusercontent.com/72019227/369600797-4d766642-e99f-4635-b7cf-25559df85456.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjQ4NzAsIm5iZiI6MTcyNjkyNDU3MCwicGF0aCI6Ii83MjAxOTIyNy8zNjk2MDA3OTctNGQ3NjY2NDItZTk5Zi00NjM1LWI3Y2YtMjU1NTlkZjg1NDU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDEzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNDdjZTI4ODE5YTk4NGU0ZjFhNzE5ZGM1MmMxODE1ZmUzYjQwZDEzYzk5MDljNjBiYmM2ZGZmYzZiMWY2YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9VALNurnesX7rAWcQHmwCMfud2jNOVmsCzVDqWMjX7w) ](https://private-user-images.githubusercontent.com/72019227/369600797-4d766642-e99f-4635-b7cf-25559df85456.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjQ4NzAsIm5iZiI6MTcyNjkyNDU3MCwicGF0aCI6Ii83MjAxOTIyNy8zNjk2MDA3OTctNGQ3NjY2NDItZTk5Zi00NjM1LWI3Y2YtMjU1NTlkZjg1NDU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDEzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNDdjZTI4ODE5YTk4NGU0ZjFhNzE5ZGM1MmMxODE1ZmUzYjQwZDEzYzk5MDljNjBiYmM2ZGZmYzZiMWY2YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9VALNurnesX7rAWcQHmwCMfud2jNOVmsCzVDqWMjX7w) [ ](https://private-user-images.githubusercontent.com/72019227/369600797-4d766642-e99f-4635-b7cf-25559df85456.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjQ4NzAsIm5iZiI6MTcyNjkyNDU3MCwicGF0aCI6Ii83MjAxOTIyNy8zNjk2MDA3OTctNGQ3NjY2NDItZTk5Zi00NjM1LWI3Y2YtMjU1NTlkZjg1NDU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDEzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNDdjZTI4ODE5YTk4NGU0ZjFhNzE5ZGM1MmMxODE1ZmUzYjQwZDEzYzk5MDljNjBiYmM2ZGZmYzZiMWY2YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9VALNurnesX7rAWcQHmwCMfud2jNOVmsCzVDqWMjX7w)
> 
> I worked around the issue with [this](https://stackoverflow.com/a/657484/12887055) answer on stackoverflow.

Fixed.
