### ISSUE TITLE
Recommended configuration inserts `<cr>` when there's no match

### ISSUE THREAD

**Issue by luiz00martins** [kevinhwang91/nvim-hlslens#65]
## Description
Recommended minimal configuration mappings inserts `<cr>` when no match is found. I assume it is because of the double `<CR>` in the mapping.

https://github.com/kevinhwang91/nvim-hlslens/assets/43142209/55a1566b-7ad4-44f3-a6e8-8ce0bb9ebb69

## Recommended Solution
Use a `|` between the commands instead:
```lua
vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n') | lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N') | lua require('hlslens').start()<CR>]],
    kopts)
```

**Comment by luiz00martins** [comment]
Just traced it back. It happens when paired with [noice](https://github.com/folke/noice.nvim).

**Comment by rockyzhang24** [comment]
Definitely it's caused by noice.
