### ISSUE TITLE
[Question]How to config map both `'normal! ' . v:count1 . 'n'` and nvim-ufo

### ISSUE THREAD

**Issue by jqhr** [kevinhwang91/nvim-hlslens#66]
I want to map `'normal! ' . v:count1 . 'n'` and nvim-ufo, but I cannot find how to map `'normal! ' . v:count1 . 'n'` and *function nN*
![图片](https://github.com/kevinhwang91/nvim-hlslens/assets/23305067/aa7ebb51-15b0-4d6b-afb2-bd94ccf03371)

**Comment by kevinhwang91** [comment]
Follow the code snippet should work.

**Comment by jqhr** [comment]
Oh, sorry.I make a mistack here.
I want to map *n* act as `v:searchforward`. it means whatever I use "*" or "#", the *n* key was always search down.
```viml
nnoremap <expr> n  'nN'[v:searchforward]
xnoremap <expr> n  'nN'[v:searchforward]
onoremap <expr> n  'nN'[v:searchforward]
```
I want to map *n* both *nN[v:searchforward]* and lua function *nN*.

**Comment by jqhr** [comment]
@kevinhwang91

**Comment by kevinhwang91** [comment]
```diff
diff --git a/README.md b/README.md
index a9e9a9d..df24efe 100644
--- a/README.md
+++ b/README.md
@@ -270,6 +270,7 @@ use {'kevinhwang91/nvim-ufo', requires = 'kevinhwang91/promise-async'}
 
 -- if Neovim is 0.8.0 before, remap yourself.
 local function nN(char)
+    vim.v.searchforward=1
     local ok, winid = hlslens.nNPeekWithUFO(char)
     if ok and winid then
         -- Safe to override buffer scope keymaps remapped by ufo,
```

**Comment by jqhr** [comment]
Thank you very much.
But it dones't work.
here is my config.
![图片](https://github.com/kevinhwang91/nvim-hlslens/assets/23305067/8b85f9f1-b2c7-425b-94dc-105c79cbc3f5)

**Comment by kevinhwang91** [comment]
Enjoy yourself, can't help anymore.

**Comment by jqhr** [comment]
Thank you, I have find out how to get it.
Add those code 
![图片](https://github.com/kevinhwang91/nvim-hlslens/assets/23305067/65631710-f90c-4308-8085-62d0f66196ee)
