### ISSUE TITLE
Improper alignment of search_count when the end of line containing search pattern is close to edge

### ISSUE THREAD

**Issue by shreyas-a-s** [kevinhwang91/nvim-hlslens#69]
`nvim --version`:
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/8lha6b5nfqjs6chngh67zjq2qp19r34b-neovim-unwrapped-0.9.5/share/nvim
"
`Operating system/version`:
Debian 12 (bookworm)

**Describe the bug**
Currently search count is shown at the end of line containing the search result. But this causes a problem when that line's end is close to edge of window.

**Steps to reproduce the behavior:**
1. Enable the plugin
2. Relaunch neovim
3. Open a dummy file that contains a line which goes to the edge of window (If it's a new file, first type the line, save it, and then open it again in neovim otherwise search_count somehow doesn't work)
5. Go to normal mode
6. Search for a word in that line using `/`
7. See the placement of search_count

**Expected behavior**
Search_count should be shown in a consistent place. An example would be the on the next line, aligned to right-most place.

**Video**

[Screencast from 2024-03-09 13-02-34.webm](https://github.com/kevinhwang91/nvim-hlslens/assets/137637016/1287b9f9-ef6e-4bd7-b2a4-90f41810cb88)

The first line's end is not close to window edge hence search_count is shown correctly. But the next line since its end is close to edge of window, search_count is shown all over the place with no specific placement.

**Comment by kevinhwang91** [comment]
```
    nearest_float_when = {
        description = [[When to open the floating window for the nearest lens.
            'auto': floating window will be opened if room isn't enough for virtual text;
            'always': always use floating window instead of virtual text;
            'never': never use floating window for the nearest lens]],
        default = 'auto',
    },
```

**Comment by shreyas-a-s** [comment]
Didn't know it was a feature. I should've read the documentation first. Thanks for the reply.
