### ISSUE TITLE
How to change matches color

### ISSUE THREAD

**Issue by vpeopleonatank** [kevinhwang91/nvim-hlslens#7]
By default install, my other matching words have hard-to-read background color. How can I change it?
![image](https://user-images.githubusercontent.com/30976876/118432928-11b8ad80-b704-11eb-946d-b8e5eecbf66d.png)

**Comment by kevinhwang91** [comment]
:hi link HlSearchLens yours

**Comment by alexzanderr** [comment]
```viml
:hi link HlSearchLens red
```
doesnt work. or it should be hexa decimal?
