### ISSUE TITLE
Integration with smooth scroll plugins

### ISSUE THREAD

**Issue by simonmandlik** [kevinhwang91/nvim-hlslens#71]
Hi, is there a recommended way to make `hlslens` work with smooth scroll plugins when `calm_down` is enabled?

Here's my attempt for integration with `cinnamon.nvim`:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    {
        "kevinhwang91/nvim-hlslens",
        opts = {
            calm_down = true,
        }
    },
    {
        'declancm/cinnamon.nvim',
        opts = {}
    }
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

local kopts = {noremap = true, silent = true}

vim.api.nvim_set_keymap('n', 'n', [[<Cmd>lua Scroll("n", 1, 1); require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'N', [[<Cmd>lua Scroll("N", 1, 1); require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', '*', [[<Cmd>lua Scroll("*", 1, 1); require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', '#', [[<Cmd>lua Scroll("#", 1, 1); require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g*', [[<Cmd>lua Scroll("g*", 1, 1); require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g#', [[#<Cmd>lua Scroll("g#", 1, 1); require('hlslens').start()<CR>]], kopts)
```

This MWE works fine only when `calm_down = false`. When `calm_down = true`, hlslens markers are shown on every second press of `"n"`.

Testing buffer: `ia<Esc>20o<Esc>ggyG10P`

https://github.com/kevinhwang91/nvim-hlslens/assets/16707112/0758f6b3-9023-4036-a711-d13d5e40e2bb

Thanks!

**Comment by kevinhwang91** [comment]
Can't reproduce it maybe I misunderstood the issue.

The lens disappears if the position is out of range after scrolling.

**Comment by simonmandlik** [comment]
In "plain" hlslens with `calm_down = false`, pressing `n` (or `N`) doesn't hide the highlighting + markers even if I smooth scroll.

But with `calm_down = true` and the MWE config, every second lens is shown (`[2/11]`, then `[4/11]`, etc...). While smooth scrolling, cursor appears in out of range positions, so it makes sense that the lens disappears, however, I would expect the `require('hlslens').start()` call to display it again.

And I have no idea why it happens on every other press.

**Comment by simonmandlik** [comment]
Try not scrolling with `<C-{u, d, f, b}>` but just by pressing `n` or `N`.

**Comment by kevinhwang91** [comment]
How does typing  `n` fire the smooth scrolling? Only get a position changed result without being out of range.

**Comment by kevinhwang91** [comment]
Actually,  it should do this on `declancm/cinnamon.nvim` side, `Scroll` should add a callback function if the animation ends.

hlslens compute the cursor position and clear lens within `throttle` that needs a fast refresh. Using `debounce` is a bad user experience.
