### ISSUE TITLE
Only highlight current match when cursor is on the match

### ISSUE THREAD

**Issue by nullromo** [kevinhwang91/nvim-hlslens#72]
**Describe problem**
There are 2 highlight colors for searching. The current match, and other matches. Now, the current match highlight appears on the match _closest to_ the cursor. That's not quite right. It shouldn't appear unless the cursor is literally on the match.

**Describe solution**
The current match highlight should appear when the cursor is on the match. When the cursor is moved off of a match, all matches should be highlighted in the non-current match color.

**Describe alternatives**
Haven't found a way around this.

**Additional context**

Here is a video of the current behavior:

https://github.com/user-attachments/assets/a17e6d63-69b5-46fa-afd9-ddbdbf88c983

As you can see, the red color remains on the matches even though the cursor is moving away. The red color should only appear when the cursor is **directly on top of** a match.

**Comment by kevinhwang91** [comment]
It's  a feature. `HlSearchNear` highlight group.

**Comment by nullromo** [comment]
Ok then how can I disable it? Removing the `HlSearchNear` highlight disables Vim's `CurSearch` feature.

![image](https://github.com/user-attachments/assets/4ec8db84-aefa-4d39-a350-8ffd7aaef67a)

As you can see above, I have `CurSearch` as red and `Search` as orange. With nvim-hlslens enabled and no `HlSearchNear` set, I just get everything orange all the time regardless of the cursor position.

**Comment by kevinhwang91** [comment]
`hi! link HlSearchNear None`

**Comment by nullromo** [comment]
Thank you, this worked. Previously I had tried simply deleting this line, but modifying it to explicitly `None` works.

```diff
- vim.api.nvim_set_hl(0, 'HlSearchNear', { link = 'FlashLabel' })
+ vim.api.nvim_set_hl(0, 'HlSearchNear', { link = 'None' })
```
