### ISSUE TITLE
Question: setup

### ISSUE THREAD

**Issue by rudotriton** [kevinhwang91/nvim-hlslens#8]
I'm trying to change some of the default settings, however, I noticed that they aren't taking effect. There's the `hslens.vim` file which calls the setup and setup toggles the initialized variable, so any subsequent call to `setup()` returns early. So I'm a bit confused by how any non-default settings are actually picked up.

**Comment by kevinhwang91** [comment]
Do you want to lazyload and setup later? `plugin/hlslens.vim` is executed after your `init.vim` or `init.lua`.

**Comment by rudotriton** [comment]
I must have been too tired. I did just check your dotfiles, I didn't have the `setup = [[vim.g.loaded_nvim_hlslens = 1]]`. I haven't used the `setup` key, so I didn't think about it. It's all good now.

**Comment by kevinhwang91** [comment]
Wow, but you are smart :)

**Comment by kdheepak** [comment]
Thanks for the great plugin. It took me a while to figure out that my configuration was not taking effect and to find this issue. Maybe this is should be included in the README? I expect a lot of people lazy load their plugins, and the configuration doesn't take into effect unless you add `setup = [[vim.g.loaded_nvim_hlslens = 1]],` to the packer use.

**Comment by kevinhwang91** [comment]
I will spend time supporting lazyload or add FAQ.

**Comment by kevinhwang91** [comment]
I think `setup = [[vim.g.loaded_nvim_hlslens = 1]]` is not necessary now.
